name: "KiCad CI/CD for COMChallange boards"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    paths:
      - 'hardware/BaseBoard/*.sch'
      - 'hardware/BaseBoard/*.kicad_pcb'
      - 'hardware/BaseBoard/*.kibot.yaml'
      - 'hardware/CommanderBoard/*.sch'
      - 'hardware/CommanderBoard/*.kicad_pcb'
      - 'hardware/CommanderBoard/*.kibot.yaml'
      - 'hardware/ETHBoard/*.sch'
      - 'hardware/ETHBoard/*.kicad_pcb'
      - 'hardware/ETHBoard/*.kibot.yaml'
      - 'hardware/LINBoard/*.sch'
      - 'hardware/LINBoard/*.kicad_pcb'
      - 'hardware/LINBoard/*.kibot.yaml'
      - '.github/workflows/KiBot.yml'
  pull_request:
    paths:
      - 'hardware/BaseBoard/*.sch'
      - 'hardware/BaseBoard/*.kicad_pcb'
      - 'hardware/BaseBoard/*.kibot.yaml'
      - 'hardware/CommanderBoard/*.sch'
      - 'hardware/CommanderBoard/*.kicad_pcb'
      - 'hardware/CommanderBoard/*.kibot.yaml'
      - 'hardware/ETHBoard/*.sch'
      - 'hardware/ETHBoard/*.kicad_pcb'
      - 'hardware/ETHBoard/*.kibot.yaml'
      - 'hardware/LINBoard/*.sch'
      - 'hardware/LINBoard/*.kicad_pcb'
      - 'hardware/LINBoard/*.kibot.yaml'
      - '.github/workflows/KiBot.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  KiBot:
    name: "Quick Start (action)"
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v4
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k9
      with:
        quickstart: YES

    - name: Upload results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Automatic_outputs
        path: Generated
